adjective = input("Choose a adjective: ")
place = input("Choose a place: ")
s_gray = input ("Choose a shade of gray: ")
water = input ("Choose a solid state of water: ")
food = input ("Choose a food: ")
food2 = input ("Chose another food or drink: ")

print("It's been a "+ adjective +" winter here in " + place +".")
print("For as long as we can remember, the sky has been "+s_gray)
print("and the ground has been covered with " +water)
print("We have all been surviving on a steady diet of "+ food + " and "+  food2 +".")
